### ISSUE TITLE
Use with Pager?

### ISSUE THREAD

**Issue by goodibunakov** [Droppers/AnimatedBottomBar#1]
Is it possible?

**Comment by Droppers** [comment]
I assume you mean ViewPager?

**Comment by goodibunakov** [comment]
> I assume you mean ViewPager?

ViewPager, yep ;)

**Comment by Droppers** [comment]
> > I assume you mean ViewPager?
> 
> ViewPager, yep ;)

I have added a `setupWithViewPager()` method, use version 1.0.2 :)!

**Comment by goodibunakov** [comment]
Great! I'll try

**Comment by Droppers** [comment]
I have added an example of how to use it: https://github.com/Droppers/AnimatedBottomBar#usage-with-viewpager

The demo app also contains an example: https://github.com/Droppers/AnimatedBottomBar/blob/master/demo/src/main/java/nl/joery/demo/animatedbottombar/ViewPagerActivity.kt

**Comment by merdanch** [comment]
> I have added an example of how to use it: https://github.com/Droppers/AnimatedBottomBar#usage-with-viewpager
> 
> The demo app also contains an example: https://github.com/Droppers/AnimatedBottomBar/blob/master/demo/src/main/java/nl/joery/demo/animatedbottombar/ViewPagerActivity.kt
> 
> You'll still need to define the tabs yourself.

waiting for ViewPager2 :)

**Comment by Droppers** [comment]
@merdanch I'll implement it as soon as I have time!

**Comment by Droppers** [comment]
@merdanch I have added `setupWithViewPager2()` method!

**Comment by Droppers** [comment]
Let me know if it works as expected!

**Comment by abdulazizahwan** [comment]
> > I have added an example of how to use it: https://github.com/Droppers/AnimatedBottomBar#usage-with-viewpager
> > The demo app also contains an example: https://github.com/Droppers/AnimatedBottomBar/blob/master/demo/src/main/java/nl/joery/demo/animatedbottombar/ViewPagerActivity.kt
> > You'll still need to define the tabs yourself.
> 
> waiting for ViewPager2 :)

Page not found
