### ISSUE TITLE
This problem occurs when migrating to a project

### ISSUE THREAD

**Issue by scc897577** [Droppers/AnimatedBottomBar#11]
The following classes could not be instantiated:
- nl.joery.animatedbottombar.AnimatedBottomBar (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.  Exception Details java.lang.IllegalArgumentException: Unknown color   at android.graphics.Color.parseColor(Color.java:1391)   at com.android.layoutlib.bridge.android.BridgeContext.resolveThemeAttribute(BridgeContext.java:412)   at android.content.res.Resources_Theme_Delegate.resolveAttribute(Resources_Theme_Delegate.java:97)   at android.content.res.Resources$Theme.resolveAttribute(Resources.java:1578)   at nl.joery.animatedbottombar.ExtensionsKt.getTextColor(Extensions.kt:20)   at nl.joery.animatedbottombar.AnimatedBottomBar.initAttributes(AnimatedBottomBar.kt:57)   at nl.joery.animatedbottombar.AnimatedBottomBar.<init>(AnimatedBottomBar.kt:50)   at nl.joery.animatedbottombar.AnimatedBottomBar.<init>(AnimatedBottomBar.kt:27)   at nl.joery.animatedbottombar.AnimatedBottomBar.<init>(AnimatedBottomBar.kt:-1)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:863)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)   at android.view.LayoutInflater.inflate(LayoutInflater.java:515)

**Comment by Droppers** [comment]
Can you provide the XML of the AnimatedBottomBar?

As a solution: try to define both the `abb_tabColor` and `abb_tabColorActive` attributes.

**Comment by scc897577** [comment]
thanks
