### ISSUE TITLE
How to add a badge or indicator ?

### ISSUE THREAD

**Issue by codeslu** [Droppers/AnimatedBottomBar#15]
How to add a badge or a number indicator to the bottom bar?

**Comment by Droppers** [comment]
At the moment this is not possible and to be honest, I don't really know how I would implement this visually.

Where would a badge / number indicator for the "Bread" item be located in this instance? I am welcome for suggestions!
<img src="https://raw.githubusercontent.com/Droppers/AnimatedBottomBar/master/media/static/type-icon.png" width="340" />

**Comment by codeslu** [comment]
Maybe you can add the indicator like whatsapp unread chat indicator
![image](https://user-images.githubusercontent.com/51796141/86275878-41d28d00-bbd4-11ea-893a-a546d622ea0d.jpeg)

**Comment by Droppers** [comment]
That sounds like an option.

<img src="https://i.imgur.com/wSpgYPT.png" width="600">

**Comment by codeslu** [comment]
Looks great
would be nice if you give control to badge attributes (color ,size ,font.... etc)

**Comment by brookmg** [comment]
Is this currently being implemented?

**Comment by Droppers** [comment]
@brookmg afaik I completed it, but I did not commit it yet since making the documentation for it is time-consuming. I'll try to look at it as soon as possible, to see if it is finished or not, I am not sure anymore.

**Comment by Droppers** [comment]
@brookmg I have committed the changes for badges, and also updated the README. Could you check if those features are sufficient?

**Comment by brookmg** [comment]
Awesome. I will check it out right now

**Comment by Droppers** [comment]
@brookmg you can also look in the demo app, I'll release it as soon as possible.

**Comment by Droppers** [comment]
This is now available, released version 1.0.9: `implementation 'nl.joery.animatedbottombar:library:1.0.9'`.
