### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by goodibunakov** [Droppers/AnimatedBottomBar#2]
`Fatal Exception: java.lang.IllegalStateException
newView must not be null

nl.joery.animatedbottombar.TabIndicator.setSelectedIndex (TabIndicator.kt:161)
nl.joery.animatedbottombar.AnimatedBottomBar$initAdapter$1.invoke (AnimatedBottomBar.kt:184)
nl.joery.animatedbottombar.AnimatedBottomBar$initAdapter$1.invoke (AnimatedBottomBar.kt:23)
nl.joery.animatedbottombar.TabAdapter.selectTab (TabAdapter.kt:104)
nl.joery.animatedbottombar.AnimatedBottomBar.selectTab (AnimatedBottomBar.kt:373)
nl.joery.animatedbottombar.AnimatedBottomBar.selectTabAt (AnimatedBottomBar.kt:353)
nl.joery.animatedbottombar.AnimatedBottomBar.selectTabAt$default (AnimatedBottomBar.kt:347)
nl.joery.animatedbottombar.AnimatedBottomBar$setupWithViewPager2$1.onPageSelected (AnimatedBottomBar.kt:426)`

I use AnimatedBottomBar with ViewPager2. I have only 2 tabs. Select second and rotate device.

ps by the way, demo.apk is not exist and your demo is not compiling. please, take a look.

**Comment by Droppers** [comment]
Thank you for reporting! Demo not compiling might be caused by me using Android Studio 4.0.

I have fixed your issue!

**Comment by goodibunakov** [comment]
everything seems to be fine now. thanks a lot.
