### ISSUE TITLE
Allow to reset selection 

### ISSUE THREAD

**Issue by AlaaZarifa** [Droppers/AnimatedBottomBar#20]
I have a use case where when the user selects a tab, a certain view would show. then if the user reselects that tab that view would disappear, but I can't find a way to deselect the tab or reset the selection.

I managed to handle this using this useful callback:

```
mainBar.onTabReselected = { tab ->
                when (tab?.id) {
                    R.id.fontSize -> {
                        seekBarView.reverseVisibility()
                         //  mainBar.resetSelection()   or   tab.deselect()
                    }
                   // other code
                }
            }
```

**Comment by Droppers** [comment]
What does reset the selection mean? You can select a tab programmatically by doing one of the following:

```kotlin
// Selecting a tab by object reference
val tabToSelect = AnimatedBottomBar.tabs[1]
AnimatedBottomBar.selectTab(tabToSelect)

// Selecting a tab at a specific position
AnimatedBottomBar.selectTabAt(1)

// Selecting a tab by the given ID resource
AnimatedBottomBar.selectTabById(R.id.tab_home)
```

**Comment by AlaaZarifa** [comment]
here's a visual explanation of what I want to achieve.
When the user clicks again on **Font Size** tab, I want the selection to be gone and return to the original look.  

![screenshot-1609848761005](https://user-images.githubusercontent.com/18426012/103645472-b3630d80-4f60-11eb-803e-4fa62896e070.jpg)

**Comment by Droppers** [comment]
Added a `clearSelection()` function which will be available in the next version.

**Comment by rgocal** [comment]
was this added yet?

**Comment by rgocal** [comment]
solved my problem by just manually adding library as a module
