### ISSUE TITLE
 does not have a NavController set

### ISSUE THREAD

**Issue by Suret1** [Droppers/AnimatedBottomBar#23]
hi, how can use setupWithNavController?  i want use your lib but also share data between fragments, I will be glad you help

this my mainacitivity

![1](https://user-images.githubusercontent.com/19667419/105420135-45edf700-5c59-11eb-97db-8982f5999ecf.jpg)

this error 

![2](https://user-images.githubusercontent.com/19667419/105420318-92393700-5c59-11eb-86b4-b815f8f79fc0.jpg)

**Comment by Droppers** [comment]
That exception does not appear to be related to this library.
