### ISSUE TITLE
Always trigger OnTabInterceptListener

### ISSUE THREAD

**Issue by danbo2468** [Droppers/AnimatedBottomBar#3]
Ability to trigger OnTabInterceptListener even when the clicked tab is the currently selected tab.

**Comment by Droppers** [comment]
What would be the use-case for this?

**Comment by danbo2468** [comment]
In my application, I open a new fragment by clicking a button on the initial fragment. The bottom navigation state won't be changed at that moment, so the same item remains selected. When the user clicks the already selected item again, the initial fragment should be shown. At this moment, I can't achieve that since the listener won't get triggered.

**Comment by Droppers** [comment]
If I understand correctly, you want the user to be able to return to the top level fragment whenever he presses a selected tab again?

I think adding a `onTabReselected`

**Comment by danbo2468** [comment]
Yes, that sounds great. That might even be better!

**Comment by Droppers** [comment]
@danbo2468 it is available now in version `1.0.5` :)!

**Comment by danbo2468** [comment]
Thank you! You're the best!
