### ISSUE TITLE
Add function to set icons programatically

### ISSUE THREAD

**Issue by russellbanks** [Droppers/AnimatedBottomBar#30]
It would be great to have the feature to set icons for the bottom bar programmatically as it would mean that any third party libraries such as [Android Iconics](https://github.com/mikepenz/Android-Iconics) can be utilised so that drawable resources do not have to be used in XML and can be created programmatically instead.

`bottomBar.tabs[i].icon = customIcon` currently says `Val cannot be reassigned`.

**Comment by Droppers** [comment]
You can already pass a drawable to the createTab() function, do you mean changing the tab icon after it has been created?

**Comment by russellbanks** [comment]
Thank you for your reply. Although this didn't work for me, it was what I was looking for :)
