### ISSUE TITLE
Fragment is don't Destroy!

### ISSUE THREAD

**Issue by Ryuk-C** [Droppers/AnimatedBottomBar#32]
I am using recyclerview adapter in my application. It loads the data over and over again every time I come to the page. How can I prevent this?

Example İmage :
https://ibb.co/XZmTGyV
https://ibb.co/7g3b03F

`
    private lateinit var binding: ActivityBeeSystemMainBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityBeeSystemMainBinding.inflate(layoutInflater)
        setContentView(binding.root)

        //Fragmnets calling
        val TestAnaSayfa = TestAnaSayfa()
        // val AkademiAnasayfaFragment = AkademiAnasayfaFragment()
        // val AnalizFragment = AnalizFragment()
        // val HesabimFragment = HesabimFragment()

        //default fragmnet
        makeCurrentFragment(TestAnaSayfa)

        binding.bottomBar.setOnTabSelectListener(object : AnimatedBottomBar.OnTabSelectListener {
            override fun onTabSelected(
                lastIndex: Int,
                lastTab: AnimatedBottomBar.Tab?,
                newIndex: Int,
                newTab: AnimatedBottomBar.Tab
            ) {

                when (newIndex) {

                    0 -> makeCurrentFragment(TestAnaSayfa);
                    //   1 -> makeCurrentFragment(AkademiAnasayfaFragment);
                    //   2 -> makeCurrentFragment(AnalizFragment);
                    //   3 -> makeCurrentFragment(HesabimFragment);
                    else -> makeCurrentFragment(TestAnaSayfa);
                }

                Log.d("bottom_bar", "Selected index: $newIndex, title: ${newTab.title}")
            }

            // An optional method that will be fired whenever an already selected tab has been selected again.
            override fun onTabReselected(index: Int, tab: AnimatedBottomBar.Tab) {

            }
        })

    }

    override fun onBackPressed() {

        val count = supportFragmentManager.backStackEntryCount

        if (count == 0) {

            if (binding.bottomBar.selectedIndex == 0) {
                super.onBackPressed()

            } else {

                binding.bottomBar.selectedIndex == 0
                binding.bottomBar.selectTabAt(0)
                makeCurrentFragment(TestAnaSayfa())
            }

        } else {
            supportFragmentManager.popBackStack()
        }

    }

    override fun onActivityResult(
        requestCode: Int,
        resultCode: Int,
        data:
        Intent?
    ) {
        super.onActivityResult(requestCode, resultCode, data)

        for (fragment in supportFragmentManager.fragments) {
            fragment.onActivityResult(requestCode, resultCode, data)
        }

    }

    private fun makeCurrentFragment(fragment: Fragment) {

        if (fragment != null) {

            supportFragmentManager.popBackStack();

            supportFragmentManager
                .beginTransaction()
                .replace(R.id.fragmentTutucu, fragment)
                .commit()
        }
    }`

**Comment by Droppers** [comment]
I am sorry but I don't think your issue is related to the library itself, if it is, feel free to reopen the issue!
