### ISSUE TITLE
Icon padding?

### ISSUE THREAD

**Issue by vexonius** [Droppers/AnimatedBottomBar#4]
Hi, thinking about using this library for my app, but supplying a bottom bar with png drawables makes the icons look big and distasteful. Is there an option to add padding or margin for icons in xml? Thanks

**Comment by Droppers** [comment]
Good point! I have only tested it with vector drawables so I completely missed it!

I will add a iconSize attribute to solve this :)!

**Comment by Droppers** [comment]
I have released version `1.0.7`, can you verify it is working?

**Comment by vexonius** [comment]
Sure, later tonight I'll check it out! Thanks for the quick response, you rock!

**Comment by vexonius** [comment]
Yes, everything works great! Thanks!

![image](https://user-images.githubusercontent.com/28738980/77378705-058ec580-6d77-11ea-9f5a-90b3c65f9fd8.png)
