### ISSUE TITLE
how do i do it on java?

### ISSUE THREAD

**Issue by LuckyD0e001** [Droppers/AnimatedBottomBar#43]
Can you help me please? How do I use the library in java

**Comment by zboing** [comment]
binding.bottomBar.setOnTabSelectListener(new AnimatedBottomBar.OnTabSelectListener() {
            @Override
            public void onTabSelected(int i, @Nullable AnimatedBottomBar.Tab tab, int i1, @NonNull AnimatedBottomBar.Tab tab1) {
                Log.d(TAG,""+tab1.getTitle());
            }

            @Override
            public void onTabReselected(int i, @NonNull AnimatedBottomBar.Tab tab) {

            }
        });
