### ISSUE TITLE
Disable tabs

### ISSUE THREAD

**Issue by Riflin** [Droppers/AnimatedBottomBar#6]
Hi! I have just tried your lib in an application and, although I know we can intercept some tabs with the OnTabInterceptedListener, I would love to have the possibility to completely disable some tabs, preventing the user to click on them and displaying the icon with another color (i.e, in my application the icons are shown in blue and the disabled ones in grey).

In my application, the users need to complete some data to advance to the next section, so it would be great to only enable those tabs when the data is completed.

Could it be possible to implement this feature?

Thanks a lot!!!

**Comment by Droppers** [comment]
I have added it! It will be available in the next release.

**Comment by Riflin** [comment]
That's awesome!!! Thank you very much!

Looking forward for the next release already... :D

**Comment by Droppers** [comment]
@Riflin please try version `1.0.8` :)

**Comment by Riflin** [comment]
It's perfect!! Thanks A LOT!

Your library is awesome!

**Comment by Droppers** [comment]
Thank you :)!
