### ISSUE TITLE
How to use fragment with whis AnimatedBottomBar

### ISSUE THREAD

**Issue by abdulazizahwan** [Droppers/AnimatedBottomBar#7]
How do we use fragment with this library? Let say i want to change FrameLayout with fragmentLayout base on position. Let say when we on Home, so my FrameLayout change to fragment_home. Is it possible to use switch case programatically?

**Comment by Droppers** [comment]
I am not sure if I am understanding your question, but on the `onTabSelected` listener you could switch based on tab ID or index and determine the new fragment?

A very basic example would be something like this:
```kotlin
bottom_bar.onTabSelected = {
    val newFragment: Fragment? = when (it.id) {
        R.id.home -> HomeFragment.newInstance()
        R.id.search -> SearchFragment.newInstance()
        R.id.account -> AccountFragment.newInstance()
        else -> null
    }

    if (newFragment != null) {
        supportFragmentManager.beginTransaction()
            .replace(R.id.fragment_container, newFragment).commit()
    }
}
```

**Comment by abdulazizahwan** [comment]
Is this Java?

**Comment by abdulazizahwan** [comment]
I'm trying to write code like this, but it doesn't work 

`bottomBar.setOnTabSelectListener(new AnimatedBottomBar.OnTabSelectListener() {
            @Override
            public void onTabSelected(int id, @Nullable AnimatedBottomBar.Tab tab, int i1, @NotNull AnimatedBottomBar.Tab tab1) {
                Fragment fragment = null;

                switch (id){
                    case R.id.home:
                        fragment = new HomeFragment();
                        break;
                }

                if (fragment!=null){
                    fragmentManager = getSupportFragmentManager();
                    fragmentManager.beginTransaction()
                            .replace(R.id.fragment_container, fragment)
                            .commit();
                }
            }
        });`

**Comment by Riflin** [comment]
It's Kotlin, but you can translate it to Java easilyk

botoom_bar.setOnTabSelectListener(new OnTabSelectListener() {
    public void onTabSelected(int lastIndex, AnimatedBottomBar.Tab lastTab, int newIndex, AnimatedBottomBar.Tab newTab) {
         Fragment fragment = null;
         switch (newTab.getId()) {
                case R.id.home:
                        fragment = HomeFragment.newInstance();
                        break;
         }

         if (fragment != null) {
                 getSupportFragmentManager().beginTransaction()
            .replace(R.id.fragment_container, newFragment).commit()
         }
}


Kotlin is better, by the way :). Try it!

**Comment by abdulazizahwan** [comment]
I'm going to try it, soon 😁

**Comment by abdulazizahwan** [comment]
Thanks a lot for the solution, it's work
